lib/two_fa_demo_web/router.ex
defmodule TwoFaDemoWeb.Router do
  use TwoFaDemoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug TwoFaDemoWeb.Plugs.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TwoFaDemoWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, except: [:index]
    resources "/sessions", SessionController, except: [:delete]
  end

  scope "/", TwoFaDemoWeb do
    pipe_through :browser
    pipe_through :protected

    get "/users", UserController, :index
    delete "/sessions", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", TwoFaDemoWeb do
  #   pipe_through :api
  # end
end

lib/two_fa_demo/accounts/user.ex
defmodule TwoFaDemo.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "accounts_users" do
    field :email,             :string
    field :login_attempts,    :integer, null: false, default: 0
    field :locked_at,         :utc_datetime_usec
    field :password_hash,     :string
    field :password,          :string, virtual: true

    timestamps()
  end

  @doc false
  def create_user_changeset(user, attrs) do
    user
    |> cast(attrs, [:email, :password])
    |> validate_required([:email, :password])
    |> put_password_hash()
  end

  def update_user_changeset(user, attrs) do
    user
    |> cast(attrs, [:email])
    |> validate_required([:email])
  end

  def lock_unlock_changeset(user, attrs) do
    user
    |> cast(attrs, [:login_attempts, :locked_at])
    |> validate_required([:login_attempts])
  end

  defp put_password_hash(%Ecto.Changeset{valid?: true, changes: %{password: password}} = changeset) do
    change(changeset, Argon2.add_hash(password))
  end

  defp put_password_hash(changeset), do: changeset
end

lib/two_fa_demo_web/controllers/user_controller.ex
defmodule TwoFaDemoWeb.UserController do
  use TwoFaDemoWeb, :controller

  alias TwoFaDemo.Accounts
  alias TwoFaDemo.Accounts.User

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

end

lib/two_fa_demo_web/views/user_view.ex
defmodule TwoFaDemoWeb.UserView do
  use TwoFaDemoWeb, :view
end

lib/two_fa_demo_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/two_fa_demo_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :email %>
  <%= text_input f, :email %>
  <%= error_tag f, :email %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/two_fa_demo_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.email %></td>

      <td>
        <span><%= link "Show", to: Routes.user_path(@conn, :show, user) %></span>
        <span><%= link "Edit", to: Routes.user_path(@conn, :edit, user) %></span>
        <span><%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>
<div>
  <%= link "Log Out", to: Routes.session_path(@conn, :delete), method: "delete" %>
</div>

lib/two_fa_demo_web/templates/user/new.html.eex
<h1>New User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/two_fa_demo_web/templates/user/show.html.eex
<h1>Show User</h1>

<ul>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>